-- BUSINESS_LOGIC.SQL - Generated by Refactor Script

CREATE OR REPLACE FUNCTION fun_generar_token_recuperacion(
    p_email tab_Usuarios.correo_usuario%TYPE
) RETURNS TABLE (
    status  TEXT,
    message TEXT,
    token   TEXT
) AS $$
DECLARE
    v_id    tab_Usuarios.id_usuario%TYPE;
    v_token TEXT;
BEGIN
    SELECT id_usuario INTO v_id
      FROM tab_Usuarios
     WHERE LOWER(correo_usuario)=LOWER(p_email)
       AND activo = TRUE;

    IF NOT FOUND THEN
        RETURN QUERY SELECT 'ERROR','Email no registrado',NULL::TEXT;
        RETURN;
    END IF;

    v_token := MD5(v_id::text || p_email || clock_timestamp()::text || random()::text);

    UPDATE tab_Usuarios
       SET token_recuperacion = v_token,
           token_expiracion   = CURRENT_TIMESTAMP + INTERVAL '1 hour',
           usr_update         = CURRENT_USER,
           fec_update         = CURRENT_TIMESTAMP
     WHERE id_usuario = v_id;

    RETURN QUERY SELECT 'SUCCESS','Token de recuperación generado', v_token;
END;
$$ LANGUAGE plpgsql;


-- ============================================
-- Recuperar contraseña con token
-- ============================================

CREATE OR REPLACE FUNCTION fun_verificar_token(
    p_id_usuario tab_Usuarios.id_usuario%TYPE,
    p_token      TEXT
) RETURNS BOOLEAN AS $$
DECLARE
    v_ultimo_acceso tab_Usuarios.ultimo_acceso%TYPE;
BEGIN
    SELECT ultimo_acceso INTO v_ultimo_acceso
      FROM tab_Usuarios
     WHERE id_usuario = p_id_usuario;

    IF NOT FOUND THEN
        RETURN FALSE;
    END IF;

    -- Aquí asumimos token "stateless"; validamos ventana de 7 días
    RETURN v_ultimo_acceso > (CURRENT_TIMESTAMP - INTERVAL '7 days');
END;
$$ LANGUAGE plpgsql;
