-- CRUD_EVENTOS.SQL - Generated by Refactor Script

CREATE OR REPLACE FUNCTION fun_insert_eventos(
    wid_evento tab_Eventos.id_evento%TYPE,
    wtitulo tab_Eventos.titulo%TYPE,
    wdescripcion tab_Eventos.descripcion%TYPE,
    wfecha_inicio tab_Eventos.fecha_inicio%TYPE,
    wfecha_fin tab_Eventos.fecha_fin%TYPE
) RETURNS TEXT AS
$BODY$
BEGIN
    IF EXISTS(SELECT 1 FROM tab_Eventos WHERE id_evento = wid_evento) THEN
        RETURN 'ERROR: El evento ya existe';
    END IF;
    
    INSERT INTO tab_Eventos (id_evento, titulo, descripcion, fecha_inicio, fecha_fin)
    VALUES (wid_evento, wtitulo, wdescripcion, wfecha_inicio, wfecha_fin);
    
    RETURN 'SUCCESS: Evento insertado correctamente';
EXCEPTION WHEN OTHERS THEN
    RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;

-- UPDATE

CREATE OR REPLACE FUNCTION fun_update_eventos(
    wid_evento tab_Eventos.id_evento%TYPE,
    wtitulo tab_Eventos.titulo%TYPE,
    wdescripcion tab_Eventos.descripcion%TYPE,
    wfecha_inicio tab_Eventos.fecha_inicio%TYPE,
    wfecha_fin tab_Eventos.fecha_fin%TYPE
) RETURNS TEXT AS
$BODY$
BEGIN
    UPDATE tab_Eventos 
    SET titulo = wtitulo, descripcion = wdescripcion,
        fecha_inicio = wfecha_inicio, fecha_fin = wfecha_fin
    WHERE id_evento = wid_evento;
    
    IF FOUND THEN
        RETURN 'SUCCESS: Evento actualizado correctamente';
    ELSE
        RETURN 'ERROR: No se encontró el evento';
    END IF;
EXCEPTION WHEN OTHERS THEN
    RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;

-- DELETE (Hard)

CREATE OR REPLACE FUNCTION fun_delete_eventos(
    wid_evento tab_Eventos.id_evento%TYPE
) RETURNS TEXT AS
$BODY$
BEGIN
    DELETE FROM tab_Eventos WHERE id_evento = wid_evento;
    
    IF FOUND THEN
        RETURN 'SUCCESS: Evento eliminado correctamente';
    ELSE
        RETURN 'ERROR: No se encontró el evento';
    END IF;
EXCEPTION WHEN OTHERS THEN
    RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;

-- ==========================================
-- NOTA: Las demás tablas (Carrito, Facturas, Envios, etc.)
-- son tablas transaccionales que generalmente NO necesitan
-- CRUDs tradicionales, sino funciones de negocio específicas.
-- Si las necesitas, avísame y las creo.
-- ==========================================
