-- CRUD_ORDENES.SQL - Generated by Refactor Script

CREATE OR REPLACE FUNCTION fun_insert_detalle_orden(
    Pid_orden               tab_Detalle_Orden.id_orden%TYPE,
    Pid_producto            tab_Detalle_Orden.id_producto%TYPE,
    Pcantidad               tab_Detalle_Orden.cantidad%TYPE,
    Pprecio_unitario        tab_Detalle_Orden.precio_unitario%TYPE,
    Pid_promocion_aplicada  tab_Detalle_Orden.id_promocion_aplicada%TYPE DEFAULT NULL
) RETURNS BOOLEAN AS
$$
DECLARE
    v_new_id_detalle_orden INT;
BEGIN
    SELECT COALESCE(MAX(id_detalle_orden), 0) + 1 INTO v_new_id_detalle_orden FROM tab_Detalle_Orden;

    INSERT INTO tab_Detalle_Orden (
        id_detalle_orden, id_orden, id_producto, cantidad, precio_unitario, id_promocion_aplicada
    ) VALUES (
        v_new_id_detalle_orden, Pid_orden, Pid_producto, Pcantidad, Pprecio_unitario, Pid_promocion_aplicada
    );

    RETURN TRUE;
EXCEPTION
    WHEN unique_violation THEN
        RAISE WARNING 'Error: El ID de detalle de orden % ya existe o el producto % ya está en la orden %.', v_new_id_detalle_orden, Pid_producto, Pid_orden;
        RETURN FALSE;
    WHEN foreign_key_violation THEN
        RAISE WARNING 'Error: La orden, producto o promoción especificada no existe. Detalles: %', SQLERRM;
        RETURN FALSE;
    WHEN check_violation THEN
        RAISE WARNING 'Error: La cantidad o precio unitario no cumplen con las restricciones. Detalles: %', SQLERRM;
        RETURN FALSE;
    WHEN OTHERS THEN
        RAISE WARNING 'Error inesperado al insertar detalle de orden: %', SQLERRM;
        RETURN FALSE;
END;
$$
LANGUAGE PLPGSQL;

-- Función para insertar un nuevo servicio de orden

CREATE OR REPLACE FUNCTION fun_checkout(
    p_id_usuario tab_Usuarios.id_usuario%TYPE,
    p_metodo_pago VARCHAR,
    p_direccion_envio VARCHAR
) RETURNS TEXT AS $$
DECLARE
    v_id_carrito tab_Carrito.id_carrito%TYPE;
    v_id_orden tab_Orden.id_orden%TYPE;
    v_total tab_Orden.total_orden%TYPE;
    v_costo_envio tab_Orden.total_orden%TYPE := 15000.00; -- Costo fijo envío
    v_stock_actual tab_Productos.stock%TYPE;
    v_item RECORD;
BEGIN
    -- 1. Obtener el carrito activo del usuario
    SELECT id_carrito INTO v_id_carrito
    FROM tab_Carrito
    WHERE id_usuario = p_id_usuario AND estado_carrito = 'activo';

    IF v_id_carrito IS NULL THEN
        RETURN 'ERROR: No hay carrito activo';
    END IF;

    -- 2. Validar Stock y Calcular Total real
    v_total := 0;
    
    FOR v_item IN 
        SELECT cd.id_producto, cd.cantidad, p.precio, p.stock
        FROM tab_Carrito_Detalle cd
        JOIN tab_Productos p ON cd.id_producto = p.id_producto
        WHERE cd.id_carrito = v_id_carrito
    LOOP
        -- Verificar si hay suficiente stock
        IF v_item.stock < v_item.cantidad THEN
            RETURN 'ERROR: Stock insuficiente para el producto ID ' || v_item.id_producto;
        END IF;
        
        -- Sumar al total
        v_total := v_total + (v_item.precio * v_item.cantidad);
    END LOOP;

    -- Si el carrito estaba vacío
    IF v_total = 0 THEN
        RETURN 'ERROR: El carrito está vacío';
    END IF;

    -- 3. Crear la Orden (Cabecera)
    -- Generar ID (simple max+1)
    SELECT COALESCE(MAX(id_orden), 0) + 1 INTO v_id_orden FROM tab_Orden;

    INSERT INTO tab_Orden (
        id_orden, id_usuario, fecha_orden, estado_orden, 
        concepto, total_orden
    ) VALUES (
        v_id_orden, 
        p_id_usuario, 
        CURRENT_TIMESTAMP, 
        'pendiente', -- Pendiente de confirmación de transferencia bancaria
        'Envío a: ' || p_direccion_envio || ' (' || p_metodo_pago || ')',
        v_total + v_costo_envio
    );

    -- 4. Mover detalles y Descontar Stock
    INSERT INTO tab_Detalle_Orden (
        id_detalle_orden, id_orden, id_producto, cantidad, precio_unitario
    )
    SELECT 
        (SELECT COALESCE(MAX(id_detalle_orden),0) FROM tab_Detalle_Orden) + ROW_NUMBER() OVER(),
        v_id_orden,
        cd.id_producto,
        cd.cantidad,
        p.precio
    FROM tab_Carrito_Detalle cd
    JOIN tab_Productos p ON cd.id_producto = p.id_producto
    WHERE cd.id_carrito = v_id_carrito;

    -- Actualizar Stock
    UPDATE tab_Productos p
    SET stock = p.stock - cd.cantidad
    FROM tab_Carrito_Detalle cd
    WHERE p.id_producto = cd.id_producto AND cd.id_carrito = v_id_carrito;

    -- 5. Cerrar el Carrito (Lo marcamos como 'convertido_a_orden')
    UPDATE tab_Carrito 
    SET estado_carrito = 'convertido_a_orden' 
    WHERE id_carrito = v_id_carrito;

    RETURN 'SUCCESS: Orden #' || v_id_orden || ' creada exitosamente';

EXCEPTION
    WHEN OTHERS THEN
        RETURN 'ERROR SQL: ' || SQLERRM;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fun_update_orden(
    Kid_orden       tab_Orden.id_orden%TYPE,
    Kid_usuario     tab_Orden.id_usuario%TYPE,
    Kestado_orden   tab_Orden.estado_orden%TYPE,
    Kconcepto       tab_Orden.concepto%TYPE,
    Ktotal_orden    tab_Orden.total_orden%TYPE
) RETURNS BOOLEAN AS
$$
BEGIN
    UPDATE tab_Orden SET
        id_usuario = Kid_usuario,
        estado_orden = Kestado_orden,
        concepto = Kconcepto,
        total_orden = Ktotal_orden
    WHERE id_orden = Kid_orden;

    IF FOUND THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
END;
$$
LANGUAGE PLPGSQL;


-- Función para actualizar una factura en tab_Facturas

CREATE OR REPLACE FUNCTION fun_insert_ordenes(
    wid_orden tab_Orden.id_orden%TYPE,
    wid_usuario tab_Orden.id_usuario%TYPE,
    westado_orden tab_Orden.estado_orden%TYPE,
    wtotal_orden tab_Orden.total_orden%TYPE,
    wconcepto tab_Orden.concepto%TYPE DEFAULT NULL
) RETURNS TEXT AS
$BODY$
    DECLARE 
        worden tab_Orden.id_orden%TYPE;
        wusuario_existe BOOLEAN;
    BEGIN
        -- Verificar si la orden ya existe
        SELECT id_orden INTO worden FROM tab_Orden WHERE id_orden = wid_orden;
        IF FOUND THEN
            RETURN 'ERROR: Orden ya existe con ID ' || wid_orden;
        END IF;
        
        -- Verificar si el usuario existe y está activo
        SELECT EXISTS(SELECT 1 FROM tab_Usuarios WHERE id_usuario = wid_usuario AND activo = TRUE) INTO wusuario_existe;
        IF NOT wusuario_existe THEN
            RETURN 'ERROR: El usuario no existe o está inactivo';
        END IF;
        
        BEGIN
            INSERT INTO tab_Orden (id_orden, id_usuario, estado_orden, total_orden, concepto)
            VALUES (wid_orden, wid_usuario, westado_orden, wtotal_orden, wconcepto);
            
            RETURN 'SUCCESS: Orden insertada correctamente con ID ' || wid_orden;
        EXCEPTION
            WHEN OTHERS THEN
                RETURN 'ERROR: ' || SQLERRM;
        END;
    END;
$BODY$
LANGUAGE PLPGSQL;

-- UPDATE - Actualizar orden

CREATE OR REPLACE FUNCTION fun_update_ordenes(
    wid_orden tab_Orden.id_orden%TYPE,
    westado_orden tab_Orden.estado_orden%TYPE,
    wconcepto tab_Orden.concepto%TYPE,
    wtotal_orden tab_Orden.total_orden%TYPE
) RETURNS TEXT AS
$BODY$
    BEGIN
        UPDATE tab_Orden SET 
            estado_orden = westado_orden,
            concepto = wconcepto,
            total_orden = wtotal_orden
        WHERE id_orden = wid_orden;
        
        IF FOUND THEN
            RETURN 'SUCCESS: Orden actualizada correctamente';
        ELSE
            RETURN 'ERROR: No se encontró la orden con ID ' || wid_orden;
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 'ERROR: ' || SQLERRM;
    END;
$BODY$
LANGUAGE PLPGSQL;

-- DELETE - Cancelar orden

CREATE OR REPLACE FUNCTION fun_cancel_ordenes(
    wid_orden tab_Orden.id_orden%TYPE
) RETURNS TEXT AS
$BODY$
    BEGIN
        UPDATE tab_Orden SET estado_orden = 'cancelado'
        WHERE id_orden = wid_orden;
        
        IF FOUND THEN
            RETURN 'SUCCESS: Orden cancelada correctamente';
        ELSE
            RETURN 'ERROR: No se encontró la orden con ID ' || wid_orden;
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 'ERROR: ' || SQLERRM;
    END;
$BODY$
LANGUAGE PLPGSQL;

-- ==========================================
-- CRUD TABLA: tab_Ciudades
-- ==========================================

-- INSERT - Insertar Ciudad
