-- CRUD_PROMOCIONES.SQL - Generated by Refactor Script

CREATE OR REPLACE FUNCTION fun_insert_promociones(
    wid_promocion tab_Promociones.id_promocion%TYPE,
    wdescripcion tab_Promociones.descripcion%TYPE,
    wdescuento tab_Promociones.descuento%TYPE,
    wfecha_inicio tab_Promociones.fecha_inicio%TYPE,
    wfecha_fin tab_Promociones.fecha_fin%TYPE
) RETURNS TEXT AS
$BODY$
BEGIN
    IF wfecha_fin < wfecha_inicio THEN
        RETURN 'ERROR: La fecha de fin debe ser posterior a la fecha de inicio';
    END IF;
    
    IF EXISTS(SELECT 1 FROM tab_Promociones WHERE id_promocion = wid_promocion) THEN
        RETURN 'ERROR: La promoción ya existe';
    END IF;
    
    INSERT INTO tab_Promociones (id_promocion, descripcion, descuento, fecha_inicio, fecha_fin)
    VALUES (wid_promocion, wdescripcion, wdescuento, wfecha_inicio, wfecha_fin);
    
    RETURN 'SUCCESS: Promoción insertada correctamente';
EXCEPTION WHEN OTHERS THEN
    RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;

-- UPDATE

CREATE OR REPLACE FUNCTION fun_update_promociones(
    wid_promocion tab_Promociones.id_promocion%TYPE,
    wdescripcion tab_Promociones.descripcion%TYPE,
    wdescuento tab_Promociones.descuento%TYPE,
    wfecha_inicio tab_Promociones.fecha_inicio%TYPE,
    wfecha_fin tab_Promociones.fecha_fin%TYPE
) RETURNS TEXT AS
$BODY$
BEGIN
    IF wfecha_fin < wfecha_inicio THEN
        RETURN 'ERROR: La fecha de fin debe ser posterior a la fecha de inicio';
    END IF;
    
    UPDATE tab_Promociones 
    SET descripcion = wdescripcion, descuento = wdescuento, 
        fecha_inicio = wfecha_inicio, fecha_fin = wfecha_fin
    WHERE id_promocion = wid_promocion;
    
    IF FOUND THEN
        RETURN 'SUCCESS: Promoción actualizada correctamente';
    ELSE
        RETURN 'ERROR: No se encontró la promoción';
    END IF;
EXCEPTION WHEN OTHERS THEN
    RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;

-- DELETE (Hard)

CREATE OR REPLACE FUNCTION fun_delete_promociones(
    wid_promocion tab_Promociones.id_promocion%TYPE
) RETURNS TEXT AS
$BODY$
BEGIN
    DELETE FROM tab_Promociones WHERE id_promocion = wid_promocion;
    
    IF FOUND THEN
        RETURN 'SUCCESS: Promoción eliminada correctamente';
    ELSE
        RETURN 'ERROR: No se encontró la promoción';
    END IF;
EXCEPTION WHEN OTHERS THEN
    RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;

-- ==========================================
-- CRUD TABLA: tab_Contacto
-- ==========================================

-- INSERT

CREATE OR REPLACE FUNCTION fun_update_promocion(
    Kid_promocion   tab_Promociones.id_promocion%TYPE,
    Kdescripcion    tab_Promociones.descripcion%TYPE,
    Kdescuento      tab_Promociones.descuento%TYPE,
    Kfecha_inicio   tab_Promociones.fecha_inicio%TYPE,
    Kfecha_fin      tab_Promociones.fecha_fin%TYPE
) RETURNS BOOLEAN AS
$$
BEGIN
    UPDATE tab_Promociones SET
        descripcion = Kdescripcion,
        descuento = Kdescuento,
        fecha_inicio = Kfecha_inicio,
        fecha_fin = Kfecha_fin
    WHERE id_promocion = Kid_promocion;

    IF FOUND THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
END;
$$
LANGUAGE PLPGSQL;


-- Función para actualizar un empleado en tab_Empleados
