-- CRUD_USUARIOS.SQL - Generated by Refactor Script

CREATE OR REPLACE FUNCTION fun_registrar_usuario(
    p_nombre     tab_Usuarios.nom_usuario%TYPE,
    p_email      tab_Usuarios.correo_usuario%TYPE,
    p_telefono   tab_Usuarios.num_telefono_usuario%TYPE,
    p_password   TEXT,
    p_direccion  tab_Usuarios.direccion_principal%TYPE DEFAULT NULL
) RETURNS TABLE (
    status       TEXT,
    message      TEXT,
    id_usuario   tab_Usuarios.id_usuario%TYPE,
    token        TEXT
) 
LANGUAGE plpgsql
AS $$
DECLARE
    v_id_usuario      tab_Usuarios.id_usuario%TYPE;
    v_email_existente BOOLEAN;
    v_salt            tab_Usuarios.salt%TYPE;
    v_password_hash   tab_Usuarios.contra%TYPE;
    v_token           TEXT;
BEGIN
    -- 1. Validar si el correo ya existe (case-insensitive recomendado)
    SELECT EXISTS(
        SELECT 1
        FROM tab_Usuarios u
        WHERE LOWER(u.correo_usuario) = LOWER(p_email)
    )
    INTO v_email_existente;

    IF v_email_existente THEN
        status     := 'ERROR';
        message    := 'El email ya está registrado';
        id_usuario := NULL;
        token      := NULL;
        RETURN NEXT;
        RETURN;
    END IF;

    -- 2. Validar longitud mínima de contraseña
    IF LENGTH(p_password) < 8 THEN
        status     := 'ERROR';
        message    := 'La contraseña debe tener al menos 8 caracteres';
        id_usuario := NULL;
        token      := NULL;
        RETURN NEXT;
        RETURN;
    END IF;

    -- 3. Generar nuevo id_usuario (si no usas secuencia/identity)
    SELECT COALESCE(MAX(u.id_usuario), 0) + 1
    INTO v_id_usuario
    FROM tab_Usuarios u;

    -- 4. Generar salt opcional (Bcrypt incluye su propio salt internamente)
    v_salt          := MD5(random()::text || clock_timestamp()::text);
    v_password_hash := p_password; -- Se asume que viene hasheado desde PHP

    -- 5. Insertar el usuario
    INSERT INTO tab_Usuarios (
        id_usuario, nom_usuario, correo_usuario, num_telefono_usuario,
        direccion_principal, fecha_registro, activo,
        contra, salt, intentos_fallidos, bloqueado,
        usr_insert, fec_insert
    ) VALUES (
        v_id_usuario, p_nombre, p_email, p_telefono,
        p_direccion, CURRENT_TIMESTAMP, TRUE,
        v_password_hash, v_salt, 0, FALSE,
        CURRENT_USER, CURRENT_TIMESTAMP
    );

    -- 6. Generar token (por ahora solo como ejemplo con MD5)
    v_token := MD5(v_id_usuario::text || p_email || clock_timestamp()::text);

    -- 7. Asignar valores de retorno
    status     := 'SUCCESS';
    message    := 'Usuario registrado correctamente';
    id_usuario := v_id_usuario;
    token      := v_token;
    RETURN NEXT;

EXCEPTION
    WHEN OTHERS THEN
        status     := 'ERROR';
        message    := 'Error al registrar: ' || SQLERRM;
        id_usuario := NULL;
        token      := NULL;
        RETURN NEXT;
END;
$$;

CREATE OR REPLACE FUNCTION fun_obtener_pedidos_usuario(
    p_id_usuario tab_Usuarios.id_usuario%TYPE
) RETURNS TABLE (
    id_orden INT,
    fecha_orden TIMESTAMP,
    estado_orden VARCHAR,
    total_orden DECIMAL,
    concepto VARCHAR
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        o.id_orden,
        o.fecha_orden,
        o.estado_orden,
        o.total_orden,
        o.concepto
    FROM tab_Orden o
    WHERE o.id_usuario = p_id_usuario
    ORDER BY o.fecha_orden DESC;
END;
$$ LANGUAGE plpgsql;

-- ==========================================
-- FUNCIÓN: Obtener dirección del usuario
-- ==========================================

CREATE OR REPLACE FUNCTION fun_obtener_direccion_usuario(
    p_id_usuario tab_Usuarios.id_usuario%TYPE
) RETURNS TABLE (
    id_direccion BIGINT,
    direccion_completa VARCHAR,
    id_ciudad SMALLINT,
    codigo_postal VARCHAR,
    es_predeterminada BOOLEAN
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        d.id_direccion,
        d.direccion_completa,
        d.id_ciudad,
        d.codigo_postal,
        d.es_predeterminada
    FROM tab_Direcciones_Envio d
    WHERE d.id_usuario = p_id_usuario
    ORDER BY d.es_predeterminada DESC
    LIMIT 1;
END;
$$ LANGUAGE plpgsql;

-- ==========================================
-- FUNCIÓN: Obtener método de pago del usuario
-- ==========================================

CREATE OR REPLACE FUNCTION fun_obtener_metodo_pago_usuario(
    p_id_usuario tab_Usuarios.id_usuario%TYPE
) RETURNS TABLE (
    id_metodo_pago SMALLINT,
    nombre_metodo VARCHAR,
    num_tarjeta VARCHAR,
    fecha_vencimiento DATE
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        mp.id_metodo_pago,
        mp.nombre_metodo,
        ump.num_tarjeta,
        ump.fecha_vencimiento
    FROM tab_Usuario_Metodo_Pago ump
    INNER JOIN tab_Metodos_Pago mp ON ump.id_metodo_pago = mp.id_metodo_pago
    WHERE ump.id_usuario = p_id_usuario
    ORDER BY ump.fec_insert DESC
    LIMIT 1;
END;
$$ LANGUAGE plpgsql;

-- ==========================================
-- FUNCIÓN: Actualizar método de pago 
-- ==========================================

CREATE OR REPLACE FUNCTION fun_cambiar_password(
    p_id_usuario      tab_Usuarios.id_usuario%TYPE,
    p_password_actual TEXT,
    p_password_nueva  TEXT
) RETURNS TABLE (
    status  TEXT,
    message TEXT
) AS $$
DECLARE
    v_u           RECORD;
    v_hash_actual tab_Usuarios.contra%TYPE;
    v_nuevo_salt  tab_Usuarios.salt%TYPE;
    v_nuevo_hash  tab_Usuarios.contra%TYPE;
BEGIN
    SELECT * INTO v_u
      FROM tab_Usuarios
     WHERE id_usuario = p_id_usuario;

    IF NOT FOUND THEN
        RETURN QUERY SELECT 'ERROR','Usuario no encontrado';
        RETURN;
    END IF;

    v_hash_actual := MD5(p_password_actual || v_u.salt);
    IF v_hash_actual <> v_u.contra THEN
        RETURN QUERY SELECT 'ERROR','Contraseña actual incorrecta';
        RETURN;
    END IF;

    IF LENGTH(p_password_nueva) < 8 THEN
        RETURN QUERY SELECT 'ERROR','La nueva contraseña debe tener al menos 8 caracteres';
        RETURN;
    END IF;

    v_nuevo_salt := MD5(random()::text || clock_timestamp()::text);
    v_nuevo_hash := MD5(p_password_nueva || v_nuevo_salt);

    UPDATE tab_Usuarios
       SET contra     = v_nuevo_hash,
           salt       = v_nuevo_salt,
           usr_update = CURRENT_USER,
           fec_update = CURRENT_TIMESTAMP
     WHERE id_usuario = p_id_usuario;

    RETURN QUERY SELECT 'SUCCESS','Contraseña actualizada correctamente';
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fun_recuperar_password(
    p_token          TEXT,
    p_password_nueva TEXT
) RETURNS TABLE (
    status  TEXT,
    message TEXT
) AS $$
DECLARE
    v_u          RECORD;
    v_nuevo_salt tab_Usuarios.salt%TYPE;
    v_nuevo_hash tab_Usuarios.contra%TYPE;
BEGIN
    IF LENGTH(p_password_nueva) < 8 THEN
        RETURN QUERY SELECT 'ERROR','La contraseña debe tener al menos 8 caracteres';
        RETURN;
    END IF;

    SELECT * INTO v_u
      FROM tab_Usuarios
     WHERE token_recuperacion = p_token
       AND token_expiracion   > CURRENT_TIMESTAMP;

    IF NOT FOUND THEN
        RETURN QUERY SELECT 'ERROR','Token inválido o expirado';
        RETURN;
    END IF;

    v_nuevo_salt := MD5(random()::text || clock_timestamp()::text);
    v_nuevo_hash := MD5(p_password_nueva || v_nuevo_salt);

    UPDATE tab_Usuarios
       SET contra            = v_nuevo_hash,
           salt              = v_nuevo_salt,
           token_recuperacion= NULL,
           token_expiracion  = NULL,
           bloqueado         = FALSE,
           intentos_fallidos = 0,
           usr_update        = CURRENT_USER,
           fec_update        = CURRENT_TIMESTAMP
     WHERE id_usuario = v_u.id_usuario;

    RETURN QUERY SELECT 'SUCCESS','Contraseña recuperada correctamente';
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fun_actualizar_perfil(
    p_id_usuario BIGINT,
    p_nombre     VARCHAR,
    p_telefono   BIGINT
) RETURNS TABLE (status TEXT, message TEXT) AS $$
BEGIN
    UPDATE tab_Usuarios
    SET nom_usuario = p_nombre,
        num_telefono_usuario = p_telefono,
        usr_update = CURRENT_USER,
        fec_update = CURRENT_TIMESTAMP
    WHERE id_usuario = p_id_usuario;

    RETURN QUERY SELECT 'SUCCESS', 'Perfil actualizado correctamente'::TEXT;
END;
$$ LANGUAGE plpgsql;

-- 2. GESTIONAR DIRECCIONES (Agregar o Actualizar)

CREATE OR REPLACE FUNCTION fun_login_usuario(
    p_email     tab_Usuarios.correo_usuario%TYPE,
    p_password  TEXT
) RETURNS TABLE (
    status     TEXT,
    message    TEXT,
    ret_id_usuario tab_Usuarios.id_usuario%TYPE,
    ret_nombre     tab_Usuarios.nom_usuario%TYPE,
    ret_email      tab_Usuarios.correo_usuario%TYPE,
    ret_telefono   tab_Usuarios.num_telefono_usuario%TYPE,
    ret_direccion  tab_Usuarios.direccion_principal%TYPE,
    ret_token      TEXT
) AS $$
DECLARE
    v_usuario        RECORD;
    v_hash           tab_Usuarios.contra%TYPE;
    v_token          TEXT;
    v_intentos       tab_Usuarios.intentos_fallidos%TYPE;
    -- Variables de retorno con tipos de la tabla
    v_ret_id         tab_Usuarios.id_usuario%TYPE;
    v_ret_nombre     tab_Usuarios.nom_usuario%TYPE;
    v_ret_email      tab_Usuarios.correo_usuario%TYPE;
    v_ret_telefono   tab_Usuarios.num_telefono_usuario%TYPE;
    v_ret_direccion  tab_Usuarios.direccion_principal%TYPE;
BEGIN
    -- Buscar por correo (case-insensitive)
    SELECT u.* INTO v_usuario
      FROM tab_Usuarios u
     WHERE LOWER(u.correo_usuario) = LOWER(p_email);

    IF NOT FOUND THEN
        status := 'ERROR';
        message := 'Credenciales inválidas';
        ret_id_usuario := NULL;
        ret_nombre := NULL;
        ret_email := NULL;
        ret_telefono := NULL;
        ret_direccion := NULL;
        ret_token := NULL;
        RETURN NEXT;
        RETURN;
    END IF;

    IF NOT v_usuario.activo THEN
        status := 'ERROR';
        message := 'Usuario inactivo. Contacte al administrador';
        ret_id_usuario := NULL;
        ret_nombre := NULL;
        ret_email := NULL;
        ret_telefono := NULL;
        ret_direccion := NULL;
        ret_token := NULL;
        RETURN NEXT;
        RETURN;
    END IF;

    IF v_usuario.bloqueado THEN
        status := 'ERROR';
        message := 'Usuario bloqueado por múltiples intentos fallidos';
        ret_id_usuario := NULL;
        ret_nombre := NULL;
        ret_email := NULL;
        ret_telefono := NULL;
        ret_direccion := NULL;
        ret_token := NULL;
        RETURN NEXT;
        RETURN;
    END IF;

    -- Verificar contraseña (DESACTIVADO EN SQL, SE HACE EN PHP)
    -- v_hash := MD5(p_password || v_usuario.salt);

    -- Éxito parcial: Encontramos el usuario, devolvemos data para que PHP verifique
    v_ret_id := v_usuario.id_usuario;
    v_ret_nombre := v_usuario.nom_usuario;
    v_ret_email := v_usuario.correo_usuario;
    v_ret_telefono := v_usuario.num_telefono_usuario;
    v_ret_direccion := COALESCE(v_usuario.direccion_principal, '');
    v_token := MD5(v_usuario.id_usuario::text || v_usuario.correo_usuario || clock_timestamp()::text);

    -- Retornar valores (status SUCCESS aquí solo significa 'Usuario Encontrado')
    status := 'SUCCESS';
    message := 'Usuario encontrado';
    ret_id_usuario := v_ret_id;
    ret_nombre := v_ret_nombre;
    ret_email := v_ret_email;
    ret_telefono := v_ret_telefono;
    ret_direccion := v_ret_direccion;
    ret_token := v_usuario.contra; -- DEVOLVEMOS EL HASH EN ESTE CAMPO PARA PHP
    RETURN NEXT;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fun_set_rol_usuario(
    p_id_usuario tab_Usuarios.id_usuario%TYPE,
    p_rol        tab_Usuarios.rol%TYPE
) RETURNS TABLE (
    status  TEXT,
    message TEXT
) AS $$
DECLARE
    v_exist BOOLEAN;
BEGIN
    -- Verificar si el usuario existe
    SELECT EXISTS(
        SELECT 1 FROM tab_Usuarios WHERE id_usuario = p_id_usuario
    ) INTO v_exist;

    IF NOT v_exist THEN
        RETURN QUERY SELECT 
            'ERROR'::TEXT,
            'Usuario no encontrado'::TEXT;
        RETURN;
    END IF;

    -- Actualizar rol
    UPDATE tab_Usuarios
       SET rol = p_rol,
           usr_update = CURRENT_USER,
           fec_update = CURRENT_TIMESTAMP
     WHERE id_usuario = p_id_usuario;

    RETURN QUERY SELECT
        'SUCCESS'::TEXT,
        'Rol actualizado correctamente'::TEXT;

END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fun_update_usuario(
    Kid_usuario             tab_Usuarios.id_usuario%TYPE,
    Knom_usuario            tab_Usuarios.nom_usuario%TYPE,
    Kcorreo_usuario         tab_Usuarios.correo_usuario%TYPE,
    Knum_telefono_usuario   tab_Usuarios.num_telefono_usuario%TYPE,
    Kdireccion_principal    tab_Usuarios.direccion_principal%TYPE,
    Kactivo                 tab_Usuarios.activo%TYPE
) RETURNS BOOLEAN AS
$$
BEGIN
    UPDATE tab_Usuarios SET
        nom_usuario = Knom_usuario,
        correo_usuario = Kcorreo_usuario,
        num_telefono_usuario = Knum_telefono_usuario,
        direccion_principal = Kdireccion_principal,
        activo = Kactivo
    WHERE id_usuario = Kid_usuario;

    -- Verifica si alguna fila fue afectada por la operación UPDATE
    IF FOUND THEN
        RETURN TRUE; -- El usuario fue encontrado y actualizado
    ELSE
        RETURN FALSE; -- El usuario no fue encontrado, no se realizó ninguna actualización
    END IF;
END;
$$
LANGUAGE PLPGSQL;


-- Función para actualizar un producto en tab_Productos

CREATE OR REPLACE FUNCTION fun_insert_usuarios(
    wid_usuario tab_Usuarios.id_usuario%TYPE,
    wnom_usuario tab_Usuarios.nom_usuario%TYPE,
    wcorreo_usuario tab_Usuarios.correo_usuario%TYPE,
    wnum_telefono_usuario tab_Usuarios.num_telefono_usuario%TYPE,
    wdireccion_principal tab_Usuarios.direccion_principal%TYPE DEFAULT NULL
) RETURNS TEXT AS
$BODY$
    DECLARE wusuario tab_Usuarios.id_usuario%TYPE;
    BEGIN
        -- Verificar si ya existe un usuario con el mismo ID o correo
        SELECT id_usuario INTO wusuario FROM tab_Usuarios
        WHERE id_usuario = wid_usuario OR correo_usuario = wcorreo_usuario;
        
        IF FOUND THEN
            RETURN 'ERROR: Usuario ya existe con ese ID o correo electrónico';
        ELSE
            BEGIN
                INSERT INTO tab_Usuarios (id_usuario, nom_usuario, correo_usuario, num_telefono_usuario, direccion_principal, activo)
                VALUES (wid_usuario, wnom_usuario, wcorreo_usuario, wnum_telefono_usuario, wdireccion_principal, TRUE);
                
                RETURN 'SUCCESS: Usuario insertado correctamente con ID ' || wid_usuario;
            EXCEPTION
                WHEN OTHERS THEN
                    RETURN 'ERROR: ' || SQLERRM;
            END;
        END IF;
    END;
$BODY$
LANGUAGE PLPGSQL;

-- UPDATE - Actualizar usuario

CREATE OR REPLACE FUNCTION fun_update_usuarios(
    wid_usuario tab_Usuarios.id_usuario%TYPE,
    wnom_usuario tab_Usuarios.nom_usuario%TYPE,
    wcorreo_usuario tab_Usuarios.correo_usuario%TYPE,
    wnum_telefono_usuario tab_Usuarios.num_telefono_usuario%TYPE,
    wdireccion_principal tab_Usuarios.direccion_principal%TYPE DEFAULT NULL
) RETURNS TEXT AS
$BODY$
    DECLARE 
        wcorreo_existente tab_Usuarios.id_usuario%TYPE;
    BEGIN
        -- Verificar si el nuevo correo ya existe en otro usuario
        SELECT id_usuario INTO wcorreo_existente FROM tab_Usuarios
        WHERE correo_usuario = wcorreo_usuario AND id_usuario != wid_usuario;
        
        IF FOUND THEN
            RETURN 'ERROR: El correo electrónico ya está registrado en otro usuario';
        END IF;
        
        -- Realizar la actualización
        UPDATE tab_Usuarios SET 
            nom_usuario = wnom_usuario,
            correo_usuario = wcorreo_usuario,
            num_telefono_usuario = wnum_telefono_usuario,
            direccion_principal = wdireccion_principal
        WHERE id_usuario = wid_usuario;
        
        IF FOUND THEN
            RETURN 'SUCCESS: Usuario actualizado correctamente';
        ELSE
            RETURN 'ERROR: No se encontró el usuario con ID ' || wid_usuario;
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 'ERROR: ' || SQLERRM;
    END;
$BODY$
LANGUAGE PLPGSQL;

-- DELETE - Eliminar usuario (soft delete)

CREATE OR REPLACE FUNCTION fun_delete_usuarios(
    wid_usuario tab_Usuarios.id_usuario%TYPE
) RETURNS TEXT AS
$BODY$
    BEGIN
        UPDATE tab_Usuarios SET activo = FALSE WHERE id_usuario = wid_usuario;
        IF FOUND THEN
            RETURN 'SUCCESS: Usuario desactivado correctamente';
        ELSE
            RETURN 'ERROR: No se encontró el usuario con ID ' || wid_usuario;
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 'ERROR: ' || SQLERRM;
    END;
$BODY$
LANGUAGE PLPGSQL;

-- ==========================================
-- CRUD TABLA: tab_Categorias 
-- ==========================================

-- INSERT - Insertar categoría
