-- CRUD_ENVIOS_LOCACIONES.SQL - Generated by Refactor Script

CREATE OR REPLACE FUNCTION fun_gestionar_direccion(
    p_id_usuario BIGINT,
    p_direccion  VARCHAR,
    p_ciudad_id  SMALLINT,
    p_postal     VARCHAR
) RETURNS TABLE (status TEXT, message TEXT) AS $$
DECLARE
    v_existe BIGINT;
    v_next_id BIGINT;
BEGIN
    -- Verificar si el usuario ya tiene una dirección
    SELECT id_direccion INTO v_existe FROM tab_Direcciones_Envio 
    WHERE id_usuario = p_id_usuario LIMIT 1;

    IF v_existe IS NOT NULL THEN
        -- Actualizar dirección existente
        UPDATE tab_Direcciones_Envio
        SET direccion_completa = p_direccion,
            id_ciudad = p_ciudad_id,
            codigo_postal = p_postal,
            usr_update = CURRENT_USER,
            fec_update = CURRENT_TIMESTAMP
        WHERE id_direccion = v_existe;
    ELSE
        -- Generar nuevo ID manualmente (sin SERIAL)
        SELECT COALESCE(MAX(id_direccion), 0) + 1 INTO v_next_id 
        FROM tab_Direcciones_Envio;
        
        -- Insertar nueva dirección
        INSERT INTO tab_Direcciones_Envio (
            id_direccion, id_usuario, direccion_completa, id_ciudad, 
            codigo_postal, es_predeterminada, usr_insert, fec_insert
        )
        VALUES (
            v_next_id, p_id_usuario, p_direccion, p_ciudad_id, p_postal, TRUE,
            CURRENT_USER, CURRENT_TIMESTAMP
        );
    END IF;

    -- SINCRONIZAR CON LA TABLA DE USUARIOS PARA COHERENCIA EN EL DASHBOARD (UI PROFILE)
    UPDATE tab_Usuarios 
    SET direccion_principal = p_direccion 
    WHERE id_usuario = p_id_usuario;

    IF v_existe IS NOT NULL THEN
        RETURN QUERY SELECT 'SUCCESS'::TEXT, 'Dirección actualizada'::TEXT;
    ELSE
        RETURN QUERY SELECT 'SUCCESS'::TEXT, 'Dirección guardada'::TEXT;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fun_insert_direcciones_envio(
    wid_direccion tab_Direcciones_Envio.id_direccion%TYPE,
    wid_usuario tab_Direcciones_Envio.id_usuario%TYPE,
    wid_ciudad tab_Direcciones_Envio.id_ciudad%TYPE,
    wdireccion_completa tab_Direcciones_Envio.direccion_completa%TYPE,
    wcodigo_postal tab_Direcciones_Envio.codigo_postal%TYPE,
    wes_predeterminada tab_Direcciones_Envio.es_predeterminada%TYPE DEFAULT FALSE
) RETURNS TEXT AS
$BODY$
DECLARE
    wusuario_existe BOOLEAN;
    wciudad_existe BOOLEAN;
BEGIN
    -- 1. Validar existencia del Usuario
    SELECT EXISTS(SELECT 1 FROM tab_Usuarios WHERE id_usuario = wid_usuario) INTO wusuario_existe;
    IF NOT wusuario_existe THEN
        RETURN 'ERROR: El usuario con ID ' || wid_usuario || ' no existe.';
    END IF;

    -- 2. Validar existencia de la Ciudad
    SELECT EXISTS(SELECT 1 FROM tab_Ciudades WHERE id_ciudad = wid_ciudad) INTO wciudad_existe;
    IF NOT wciudad_existe THEN
        RETURN 'ERROR: La ciudad con ID ' || wid_ciudad || ' no existe.';
    END IF;

    -- 3. Verificar duplicidad de ID de dirección
    IF EXISTS(SELECT 1 FROM tab_Direcciones_Envio WHERE id_direccion = wid_direccion) THEN
        RETURN 'ERROR: Ya existe una dirección registrada con el ID ' || wid_direccion;
    END IF;

    -- 4. Lógica de Dirección Predeterminada
    -- Si la nueva dirección es predeterminada, quitamos esa marca de las otras direcciones del usuario
    IF wes_predeterminada THEN
        UPDATE tab_Direcciones_Envio 
        SET es_predeterminada = FALSE 
        WHERE id_usuario = wid_usuario;
    END IF;

    BEGIN
        INSERT INTO tab_Direcciones_Envio (
            id_direccion, id_usuario, id_ciudad, direccion_completa, codigo_postal, es_predeterminada
        ) VALUES (
            wid_direccion, wid_usuario, wid_ciudad, wdireccion_completa, wcodigo_postal, wes_predeterminada
        );
        
        RETURN 'SUCCESS: Dirección de envío agregada correctamente.';
    EXCEPTION WHEN OTHERS THEN
        RETURN 'ERROR SQL: ' || SQLERRM;
    END;
END;
$BODY$ LANGUAGE PLPGSQL;


-- UPDATE - Actualizar Dirección de Envío

CREATE OR REPLACE FUNCTION fun_update_direcciones_envio(
    wid_direccion tab_Direcciones_Envio.id_direccion%TYPE,
    wid_ciudad tab_Direcciones_Envio.id_ciudad%TYPE,
    wdireccion_completa tab_Direcciones_Envio.direccion_completa%TYPE,
    wcodigo_postal tab_Direcciones_Envio.codigo_postal%TYPE,
    wes_predeterminada tab_Direcciones_Envio.es_predeterminada%TYPE
) RETURNS TEXT AS
$BODY$
DECLARE
    wusuario_propietario tab_Usuarios.id_usuario%TYPE;
    wciudad_existe BOOLEAN;
BEGIN
    -- 1. Obtener el dueño de la dirección (y verificar si la dirección existe)
    SELECT id_usuario INTO wusuario_propietario 
    FROM tab_Direcciones_Envio 
    WHERE id_direccion = wid_direccion;

    IF NOT FOUND THEN
        RETURN 'ERROR: No se encontró la dirección con ID ' || wid_direccion;
    END IF;

    -- 2. Validar nueva ciudad
    SELECT EXISTS(SELECT 1 FROM tab_Ciudades WHERE id_ciudad = wid_ciudad) INTO wciudad_existe;
    IF NOT wciudad_existe THEN
        RETURN 'ERROR: La ciudad con ID ' || wid_ciudad || ' no existe.';
    END IF;

    -- 3. Lógica de Dirección Predeterminada
    -- Si se marca como predeterminada, desmarcamos las demás de ESTE usuario
    IF wes_predeterminada THEN
        UPDATE tab_Direcciones_Envio 
        SET es_predeterminada = FALSE 
        WHERE id_usuario = wusuario_propietario AND id_direccion != wid_direccion;
    END IF;

    -- 4. Actualizar
    UPDATE tab_Direcciones_Envio 
    SET id_ciudad = wid_ciudad,
        direccion_completa = wdireccion_completa,
        codigo_postal = wcodigo_postal,
        es_predeterminada = wes_predeterminada
    WHERE id_direccion = wid_direccion;

    RETURN 'SUCCESS: Dirección actualizada correctamente.';

EXCEPTION WHEN OTHERS THEN
    RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;


-- DELETE - Eliminar Dirección (Hard Delete)

CREATE OR REPLACE FUNCTION fun_delete_direcciones_envio(
    wid_direccion tab_Direcciones_Envio.id_direccion%TYPE
) RETURNS TEXT AS
$BODY$
BEGIN
    DELETE FROM tab_Direcciones_Envio WHERE id_direccion = wid_direccion;
    
    IF FOUND THEN
        RETURN 'SUCCESS: Dirección eliminada permanentemente.';
    ELSE
        RETURN 'ERROR: No se encontró la dirección con ID ' || wid_direccion;
    END IF;

EXCEPTION 
    -- Capturar error si la dirección ya se usó en un envío (tab_Envios)
    WHEN FOREIGN_KEY_VIOLATION THEN
        RETURN 'ERROR: No se puede eliminar esta dirección porque está vinculada a un envío histórico.';
    WHEN OTHERS THEN
        RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;
-- ==========================================
-- CRUDs PARA LAS TABLAS FALTANTES
-- ==========================================

-- ==========================================
-- CRUD TABLA: tab_Subcategorias
-- ==========================================

-- INSERT
