-- CRUD_EMPLEADOS.SQL - Generated by Refactor Script

CREATE OR REPLACE FUNCTION fun_insert_empleados(
    wid_empleado tab_Empleados.id_empleado%TYPE,
    wnom_empleado tab_Empleados.nom_empleado%TYPE,
    wapellido_empleado tab_Empleados.apellido_empleado%TYPE,
    wcorreo tab_Empleados.correo%TYPE,
    wtelefono tab_Empleados.telefono%TYPE,
    wpuesto tab_Empleados.puesto%TYPE,
    wfecha_contratacion tab_Empleados.fecha_contratacion%TYPE
) RETURNS TEXT AS
$BODY$
BEGIN
    IF EXISTS(SELECT 1 FROM tab_Empleados WHERE id_empleado = wid_empleado) THEN
        RETURN 'ERROR: El empleado ya existe';
    END IF;
    
    INSERT INTO tab_Empleados (id_empleado, nom_empleado, apellido_empleado, correo, telefono, puesto, fecha_contratacion)
    VALUES (wid_empleado, wnom_empleado, wapellido_empleado, wcorreo, wtelefono, wpuesto, wfecha_contratacion);
    
    RETURN 'SUCCESS: Empleado insertado correctamente';
EXCEPTION WHEN OTHERS THEN
    RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;

-- UPDATE

CREATE OR REPLACE FUNCTION fun_update_empleados(
    wid_empleado tab_Empleados.id_empleado%TYPE,
    wnom_empleado tab_Empleados.nom_empleado%TYPE,
    wapellido_empleado tab_Empleados.apellido_empleado%TYPE,
    wcorreo tab_Empleados.correo%TYPE,
    wtelefono tab_Empleados.telefono%TYPE,
    wpuesto tab_Empleados.puesto%TYPE
) RETURNS TEXT AS
$BODY$
BEGIN
    UPDATE tab_Empleados 
    SET nom_empleado = wnom_empleado, apellido_empleado = wapellido_empleado,
        correo = wcorreo, telefono = wtelefono, puesto = wpuesto
    WHERE id_empleado = wid_empleado;
    
    IF FOUND THEN
        RETURN 'SUCCESS: Empleado actualizado correctamente';
    ELSE
        RETURN 'ERROR: No se encontró el empleado';
    END IF;
EXCEPTION WHEN OTHERS THEN
    RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;

-- DELETE (Hard)

CREATE OR REPLACE FUNCTION fun_delete_empleados(
    wid_empleado tab_Empleados.id_empleado%TYPE
) RETURNS TEXT AS
$BODY$
BEGIN
    DELETE FROM tab_Empleados WHERE id_empleado = wid_empleado;
    
    IF FOUND THEN
        RETURN 'SUCCESS: Empleado eliminado correctamente';
    ELSE
        RETURN 'ERROR: No se encontró el empleado';
    END IF;
EXCEPTION WHEN OTHERS THEN
    RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;

-- ==========================================
-- CRUD TABLA: tab_Eventos
-- ==========================================

-- INSERT

CREATE OR REPLACE FUNCTION fun_update_empleado(
    Kid_empleado            tab_Empleados.id_empleado%TYPE,
    Knum_documento          tab_Empleados.num_documento%TYPE,
    Knom_empleado           tab_Empleados.nom_empleado%TYPE,
    Kapellido_empleado      tab_Empleados.apellido_empleado%TYPE,
    Kcorreo                 tab_Empleados.correo%TYPE,
    Ktelefono               tab_Empleados.telefono%TYPE,
    Kpuesto                 tab_Empleados.puesto%TYPE,
    Kfecha_contratacion     tab_Empleados.fecha_contratacion%TYPE
) RETURNS BOOLEAN AS
$$
BEGIN
    UPDATE tab_Empleados SET
        num_documento = Knum_documento,
        nom_empleado = Knom_empleado,
        apellido_empleado = Kapellido_empleado,
        correo = Kcorreo,
        telefono = Ktelefono,
        puesto = Kpuesto,
        fecha_contratacion = Kfecha_contratacion
    WHERE id_empleado = Kid_empleado;

    IF FOUND THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
END;
$$
LANGUAGE PLPGSQL;
