-- CRUD_LOCACIONES.SQL - Generated by Refactor Script

CREATE OR REPLACE FUNCTION fun_insert_ciudades(
    wid_ciudad tab_Ciudades.id_ciudad%TYPE,
    wid_departamento tab_Ciudades.id_departamento%TYPE,
    wnombre_ciudad tab_Ciudades.nombre_ciudad%TYPE,
    wcodigo_postal tab_Ciudades.codigo_postal%TYPE DEFAULT NULL
) RETURNS TEXT AS
$BODY$
DECLARE
    wdepartamento_existe BOOLEAN;
BEGIN
    -- 1. Verificar si la ciudad ya existe por ID
    IF EXISTS(SELECT 1 FROM tab_Ciudades WHERE id_ciudad = wid_ciudad) THEN
        RETURN 'ERROR: La ciudad con ID ' || wid_ciudad || ' ya existe.';
    END IF;

    -- 2. Verificar Integridad Referencial: ¿Existe el departamento?
    SELECT EXISTS(SELECT 1 FROM tab_Departamentos WHERE id_departamento = wid_departamento) 
    INTO wdepartamento_existe;

    IF NOT wdepartamento_existe THEN
        RETURN 'ERROR: El departamento con ID ' || wid_departamento || ' no existe. No se puede crear la ciudad.';
    END IF;

    -- 3. Insertar
    BEGIN
        INSERT INTO tab_Ciudades (id_ciudad, id_departamento, nombre_ciudad, codigo_postal)
        VALUES (wid_ciudad, wid_departamento, wnombre_ciudad, wcodigo_postal);
        
        RETURN 'SUCCESS: Ciudad insertada correctamente con ID ' || wid_ciudad;
    EXCEPTION WHEN OTHERS THEN
        RETURN 'ERROR SQL: ' || SQLERRM;
    END;
END;
$BODY$ LANGUAGE PLPGSQL;


-- UPDATE - Actualizar Ciudad

CREATE OR REPLACE FUNCTION fun_update_ciudades(
    wid_ciudad tab_Ciudades.id_ciudad%TYPE,
    wid_departamento tab_Ciudades.id_departamento%TYPE,
    wnombre_ciudad tab_Ciudades.nombre_ciudad%TYPE,
    wcodigo_postal tab_Ciudades.codigo_postal%TYPE DEFAULT NULL
) RETURNS TEXT AS
$BODY$
DECLARE
    wdepartamento_existe BOOLEAN;
BEGIN
    -- 1. Verificar si el nuevo departamento existe (si se está cambiando)
    SELECT EXISTS(SELECT 1 FROM tab_Departamentos WHERE id_departamento = wid_departamento) 
    INTO wdepartamento_existe;

    IF NOT wdepartamento_existe THEN
        RETURN 'ERROR: El departamento con ID ' || wid_departamento || ' no existe.';
    END IF;

    -- 2. Actualizar
    UPDATE tab_Ciudades 
    SET id_departamento = wid_departamento,
        nombre_ciudad = wnombre_ciudad,
        codigo_postal = wcodigo_postal
    WHERE id_ciudad = wid_ciudad;

    IF FOUND THEN
        RETURN 'SUCCESS: Ciudad actualizada correctamente.';
    ELSE
        RETURN 'ERROR: No se encontró la ciudad con ID ' || wid_ciudad;
    END IF;

EXCEPTION WHEN OTHERS THEN
    RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;


-- DELETE - Eliminar Ciudad (Hard Delete)
-- Advertencia: Esto fallará si la ciudad está en uso en tab_Direcciones_Envio

CREATE OR REPLACE FUNCTION fun_delete_ciudades(
    wid_ciudad tab_Ciudades.id_ciudad%TYPE
) RETURNS TEXT AS
$BODY$
BEGIN
    DELETE FROM tab_Ciudades WHERE id_ciudad = wid_ciudad;
    
    IF FOUND THEN
        RETURN 'SUCCESS: Ciudad eliminada permanentemente.';
    ELSE
        RETURN 'ERROR: No se encontró la ciudad con ID ' || wid_ciudad;
    END IF;

EXCEPTION 
    -- Capturar error de llave foránea (si la ciudad se usa en direcciones)
    WHEN FOREIGN_KEY_VIOLATION THEN
        RETURN 'ERROR: No se puede eliminar la ciudad porque hay direcciones de envío asociadas a ella.';
    WHEN OTHERS THEN
        RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;

-- ==========================================
-- CRUD TABLA: tab_Departamentos
-- ==========================================

-- INSERT - Insertar Departamento

CREATE OR REPLACE FUNCTION fun_insert_departamentos(
    wid_departamento tab_Departamentos.id_departamento%TYPE,
    wnombre_departamento tab_Departamentos.nombre_departamento%TYPE,
    wcodigo_iso tab_Departamentos.codigo_iso%TYPE DEFAULT NULL
) RETURNS TEXT AS
$BODY$
DECLARE
    wexiste BOOLEAN;
BEGIN
    -- 1. Verificar si ya existe un departamento con ese ID o Nombre
    -- (Es importante evitar nombres duplicados como dos departamentos llamados "Antioquia")
    SELECT EXISTS(
        SELECT 1 FROM tab_Departamentos 
        WHERE id_departamento = wid_departamento OR nombre_departamento = wnombre_departamento
    ) INTO wexiste;

    IF wexiste THEN
        RETURN 'ERROR: Ya existe un departamento con ese ID o Nombre.';
    END IF;

    -- 2. Insertar
    BEGIN
        INSERT INTO tab_Departamentos (id_departamento, nombre_departamento, codigo_iso)
        VALUES (wid_departamento, wnombre_departamento, wcodigo_iso);
        
        RETURN 'SUCCESS: Departamento insertado correctamente con ID ' || wid_departamento;
    EXCEPTION WHEN OTHERS THEN
        RETURN 'ERROR SQL: ' || SQLERRM;
    END;
END;
$BODY$ LANGUAGE PLPGSQL;


-- UPDATE - Actualizar Departamento

CREATE OR REPLACE FUNCTION fun_update_departamentos(
    wid_departamento tab_Departamentos.id_departamento%TYPE,
    wnombre_departamento tab_Departamentos.nombre_departamento%TYPE,
    wcodigo_iso tab_Departamentos.codigo_iso%TYPE DEFAULT NULL
) RETURNS TEXT AS
$BODY$
DECLARE
    wnombre_duplicado BOOLEAN;
BEGIN
    -- 1. Validar duplicidad de nombre (excluyendo el registro actual)
    SELECT EXISTS(
        SELECT 1 FROM tab_Departamentos 
        WHERE nombre_departamento = wnombre_departamento AND id_departamento != wid_departamento
    ) INTO wnombre_duplicado;

    IF wnombre_duplicado THEN
        RETURN 'ERROR: Ya existe otro departamento con el nombre ' || wnombre_departamento;
    END IF;

    -- 2. Actualizar
    UPDATE tab_Departamentos 
    SET nombre_departamento = wnombre_departamento,
        codigo_iso = wcodigo_iso
    WHERE id_departamento = wid_departamento;

    IF FOUND THEN
        RETURN 'SUCCESS: Departamento actualizado correctamente.';
    ELSE
        RETURN 'ERROR: No se encontró el departamento con ID ' || wid_departamento;
    END IF;

EXCEPTION WHEN OTHERS THEN
    RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;


-- DELETE - Eliminar Departamento (Hard Delete)
-- Advertencia: Esto fallará si el departamento tiene Ciudades asociadas.

CREATE OR REPLACE FUNCTION fun_delete_departamentos(
    wid_departamento tab_Departamentos.id_departamento%TYPE
) RETURNS TEXT AS
$BODY$
BEGIN
    DELETE FROM tab_Departamentos WHERE id_departamento = wid_departamento;
    
    IF FOUND THEN
        RETURN 'SUCCESS: Departamento eliminado permanentemente.';
    ELSE
        RETURN 'ERROR: No se encontró el departamento con ID ' || wid_departamento;
    END IF;

EXCEPTION 
    -- Captura el error si intentas borrar un departamento que tiene ciudades
    WHEN FOREIGN_KEY_VIOLATION THEN
        RETURN 'ERROR: No se puede eliminar el departamento porque tiene ciudades asociadas. Elimine primero las ciudades.';
    WHEN OTHERS THEN
        RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;

-- ==========================================
-- CRUD TABLA: tab_Direcciones_Envio
-- ==========================================

-- INSERT - Insertar Dirección de Envío
