-- CRUD_MARCAS.SQL - Generated by Refactor Script

CREATE OR REPLACE FUNCTION fun_insert_marcas(
    wid_marca tab_Marcas.id_marca%TYPE,
    wnom_marca tab_Marcas.nom_marca%TYPE
) RETURNS TEXT AS
$BODY$
    DECLARE wmarca tab_Marcas.id_marca%TYPE;
    BEGIN
        -- Verificar si ya existe una marca con el mismo ID o nombre
        SELECT id_marca INTO wmarca FROM tab_Marcas
        WHERE id_marca = wid_marca OR nom_marca = wnom_marca;
        
        IF FOUND THEN
            RETURN 'ERROR: Marca ya existe con ese ID o nombre';
        ELSE
            BEGIN
        
                INSERT INTO tab_Marcas (id_marca, nom_marca, estado_marca)
                VALUES (wid_marca, wnom_marca, TRUE);
                
                RETURN 'SUCCESS: Marca insertada correctamente con ID ' || wid_marca;
            EXCEPTION
                WHEN OTHERS THEN
                    RETURN 'ERROR: ' || SQLERRM;
            END;
        END IF;
    END;
$BODY$
LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION fun_update_marcas(
    wid_marca tab_Marcas.id_marca%TYPE,
    wnom_marca tab_Marcas.nom_marca%TYPE,
    westado_marca tab_Marcas.estado_marca%TYPE DEFAULT TRUE
) RETURNS TEXT AS
$BODY$
    DECLARE
        wnombre_existente tab_Marcas.id_marca%TYPE;
    BEGIN
        SELECT id_marca INTO wnombre_existente FROM tab_Marcas
        WHERE nom_marca = wnom_marca AND id_marca != wid_marca;
        
        IF FOUND THEN
            RETURN 'ERROR: Ya existe otra marca con ese nombre';
        END IF;
        
        UPDATE tab_Marcas SET 
            nom_marca = wnom_marca,
            estado_marca = westado_marca
        WHERE id_marca = wid_marca;
        
        IF FOUND THEN
            RETURN 'SUCCESS: Marca actualizada correctamente';
        ELSE
            RETURN 'ERROR: No se encontró la marca con ID ' || wid_marca;
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 'ERROR: ' || SQLERRM;
    END;
$BODY$
LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION fun_delete_marcas(
    wid_marca tab_Marcas.id_marca%TYPE
) RETURNS TEXT AS
$BODY$
    BEGIN
        UPDATE tab_Marcas SET estado_marca = FALSE 
        WHERE id_marca = wid_marca;
        
        IF FOUND THEN
            RETURN 'SUCCESS: Marca desactivada correctamente';
        ELSE
            RETURN 'ERROR: No se encontró la marca con ID ' || wid_marca;
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 'ERROR: ' || SQLERRM;
    END;
$BODY$
LANGUAGE PLPGSQL;
-- ==========================================
-- CRUD TABLA: tab_Productos
-- ==========================================

--función de insertar productos
