-- CRUD_CATEGORIAS.SQL - Generated by Refactor Script

CREATE OR REPLACE FUNCTION fun_insert_subcategorias(
    wid_categoria tab_Subcategorias.id_categoria%TYPE,
    wid_subcategoria tab_Subcategorias.id_subcategoria%TYPE,
    wnom_subcategoria tab_Subcategorias.nom_subcategoria%TYPE
) RETURNS TEXT AS
$BODY$
DECLARE
    wcategoria_existe BOOLEAN;
BEGIN
    -- Verificar que la categoría existe
    SELECT EXISTS(SELECT 1 FROM tab_Categorias WHERE id_categoria = wid_categoria AND estado = TRUE) INTO wcategoria_existe;
    IF NOT wcategoria_existe THEN
        RETURN 'ERROR: La categoría con ID ' || wid_categoria || ' no existe o está inactiva';
    END IF;
    
    -- Verificar duplicado
    IF EXISTS(SELECT 1 FROM tab_Subcategorias WHERE id_categoria = wid_categoria AND id_subcategoria = wid_subcategoria) THEN
        RETURN 'ERROR: La subcategoría ya existe';
    END IF;
    
    INSERT INTO tab_Subcategorias (id_categoria, id_subcategoria, nom_subcategoria, estado)
    VALUES (wid_categoria, wid_subcategoria, wnom_subcategoria, TRUE);
    
    RETURN 'SUCCESS: Subcategoría insertada correctamente';
EXCEPTION WHEN OTHERS THEN
    RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;

-- UPDATE

CREATE OR REPLACE FUNCTION fun_update_subcategorias(
    wid_categoria tab_Subcategorias.id_categoria%TYPE,
    wid_subcategoria tab_Subcategorias.id_subcategoria%TYPE,
    wnom_subcategoria tab_Subcategorias.nom_subcategoria%TYPE,
    westado tab_Subcategorias.estado%TYPE DEFAULT TRUE
) RETURNS TEXT AS
$BODY$
BEGIN
    UPDATE tab_Subcategorias 
    SET nom_subcategoria = wnom_subcategoria, estado = westado
    WHERE id_categoria = wid_categoria AND id_subcategoria = wid_subcategoria;
    
    IF FOUND THEN
        RETURN 'SUCCESS: Subcategoría actualizada correctamente';
    ELSE
        RETURN 'ERROR: No se encontró la subcategoría';
    END IF;
EXCEPTION WHEN OTHERS THEN
    RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;

-- DELETE (Soft)

CREATE OR REPLACE FUNCTION fun_delete_subcategorias(
    wid_categoria tab_Subcategorias.id_categoria%TYPE,
    wid_subcategoria tab_Subcategorias.id_subcategoria%TYPE
) RETURNS TEXT AS
$BODY$
BEGIN
    UPDATE tab_Subcategorias SET estado = FALSE
    WHERE id_categoria = wid_categoria AND id_subcategoria = wid_subcategoria;
    
    IF FOUND THEN
        RETURN 'SUCCESS: Subcategoría desactivada correctamente';
    ELSE
        RETURN 'ERROR: No se encontró la subcategoría';
    END IF;
EXCEPTION WHEN OTHERS THEN
    RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;

-- ==========================================
-- CRUD TABLA: tab_Metodos_Pago
-- ==========================================

-- INSERT

CREATE OR REPLACE FUNCTION fun_insert_categorias(
    wid_categoria tab_Categorias.id_categoria%TYPE,
    wnom_categoria tab_Categorias.nom_categoria%TYPE,
    wdescripcion_categoria tab_Categorias.descripcion_categoria%TYPE
) RETURNS TEXT AS
$BODY$
    DECLARE wcategoria tab_Categorias.id_categoria%TYPE;
    BEGIN
        -- Verificar si ya existe una categoría con el mismo ID o nombre
        SELECT id_categoria INTO wcategoria FROM tab_Categorias
        WHERE id_categoria = wid_categoria OR nom_categoria = wnom_categoria;
        
        IF FOUND THEN
            RETURN 'ERROR: Categoría ya existe con ese ID o nombre';
        ELSE
            BEGIN
                INSERT INTO tab_Categorias (id_categoria, nom_categoria, descripcion_categoria, estado)
                VALUES (wid_categoria, wnom_categoria, wdescripcion_categoria, TRUE);
                
                RETURN 'SUCCESS: Categoría insertada correctamente con ID ' || wid_categoria;
            EXCEPTION
                WHEN OTHERS THEN
                    RETURN 'ERROR: ' || SQLERRM;
            END;
        END IF;
    END;
$BODY$
LANGUAGE PLPGSQL;

-- UPDATE - Actualizar categoría

CREATE OR REPLACE FUNCTION fun_update_categorias(
    wid_categoria tab_Categorias.id_categoria%TYPE,
    wnom_categoria tab_Categorias.nom_categoria%TYPE,
    wdescripcion_categoria tab_Categorias.descripcion_categoria%TYPE,
    westado tab_Categorias.estado%TYPE DEFAULT TRUE
) RETURNS TEXT AS
$BODY$
    DECLARE
        wnombre_existente tab_Categorias.id_categoria%TYPE;
    BEGIN
        -- Verificar si el nuevo nombre ya existe en otra categoría
        SELECT id_categoria INTO wnombre_existente FROM tab_Categorias
        WHERE nom_categoria = wnom_categoria AND id_categoria != wid_categoria;
        
        IF FOUND THEN
            RETURN 'ERROR: Ya existe otra categoría con ese nombre';
        END IF;
        
        -- Realizar la actualización
        UPDATE tab_Categorias SET 
            nom_categoria = wnom_categoria,
            descripcion_categoria = wdescripcion_categoria,
            estado = westado
        WHERE id_categoria = wid_categoria;
        
        IF FOUND THEN
            RETURN 'SUCCESS: Categoría actualizada correctamente';
        ELSE
            RETURN 'ERROR: No se encontró la categoría con ID ' || wid_categoria;
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 'ERROR: ' || SQLERRM;
    END;
$BODY$
LANGUAGE PLPGSQL;

-- DELETE - Eliminar categoría (soft delete)

CREATE OR REPLACE FUNCTION fun_delete_categorias(
    wid_categoria tab_Categorias.id_categoria%TYPE
) RETURNS TEXT AS
$BODY$
    BEGIN
        UPDATE tab_Categorias SET estado = FALSE WHERE id_categoria = wid_categoria;
        IF FOUND THEN
            RETURN 'SUCCESS: Categoría desactivada correctamente';
        ELSE
            RETURN 'ERROR: No se encontró la categoría con ID ' || wid_categoria;
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 'ERROR: ' || SQLERRM;
    END;
$BODY$
LANGUAGE PLPGSQL;

-- ==========================================
-- CRUD TABLA: tab_Marcas (CORREGIDO)
-- ==========================================
