-- CRUD_PAGOS.SQL - Generated by Refactor Script

CREATE OR REPLACE FUNCTION fun_actualizar_pago(
    wid_usuario          tab_Usuarios.id_usuario%TYPE,
    wid_metodo_pago      tab_Metodos_Pago.id_metodo_pago%TYPE,
    wnum_tarjeta         VARCHAR,   -- últimos 4 dígitos u otro identificador
    wfecha_vencimiento   DATE DEFAULT NULL
) RETURNS TEXT AS
$$
DECLARE
    v_reg_usuario RECORD;
    v_reg_metodo  RECORD;
BEGIN
    -- ===============================
    -- VALIDAR USUARIO
    -- ===============================
    SELECT * INTO v_reg_usuario
    FROM tab_Usuarios
    WHERE id_usuario = wid_usuario;

    IF NOT FOUND THEN
        RETURN 'ERROR: Usuario con ID ' || wid_usuario || ' no existe';
    END IF;

    IF v_reg_usuario.activo = FALSE THEN
        RETURN 'ERROR: Usuario ' || v_reg_usuario.nom_usuario || ' está inactivo';
    END IF;

    -- ===============================
    -- VALIDAR MÉTODO DE PAGO
    -- ===============================
    SELECT * INTO v_reg_metodo
    FROM tab_Metodos_Pago
    WHERE id_metodo_pago = wid_metodo_pago;

    IF NOT FOUND THEN
        RETURN 'ERROR: Método de pago con ID ' || wid_metodo_pago || ' no existe';
    END IF;

    -- ===============================
    -- ACTUALIZAR O INSERTAR PAGO
    -- ===============================
    IF EXISTS (
        SELECT 1 FROM tab_Usuario_Metodo_Pago
        WHERE id_usuario = wid_usuario
          AND id_metodo_pago = wid_metodo_pago
    ) THEN
        -- Actualizar
        UPDATE tab_Usuario_Metodo_Pago
        SET num_tarjeta = wnum_tarjeta,
            fecha_vencimiento = wfecha_vencimiento,
            usr_update = CURRENT_USER,
            fec_update = CURRENT_TIMESTAMP
        WHERE id_usuario = wid_usuario
          AND id_metodo_pago = wid_metodo_pago;

        RETURN 'SUCCESS: Método de pago actualizado correctamente';
    ELSE
        -- Insertar nuevo
        INSERT INTO tab_Usuario_Metodo_Pago (
            id_usuario, id_metodo_pago, num_tarjeta, fecha_vencimiento,
            usr_insert, fec_insert
        ) VALUES (
            wid_usuario, wid_metodo_pago, wnum_tarjeta, wfecha_vencimiento,
            CURRENT_USER, CURRENT_TIMESTAMP
        );

        RETURN 'SUCCESS: Método de pago registrado correctamente';
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        RETURN 'ERROR: ' || SQLERRM;
END;
$$
LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fun_actualizar_metodo_pago(
    p_id_usuario tab_Usuarios.id_usuario%TYPE,
    p_id_metodo_pago tab_Metodos_Pago.id_metodo_pago%TYPE,
    p_num_tarjeta VARCHAR,
    p_fecha_vencimiento DATE DEFAULT NULL
) RETURNS TABLE (
    status TEXT,
    message TEXT
) AS $$
DECLARE
    v_usuario_existe BOOLEAN;
    v_metodo_existe BOOLEAN;
BEGIN
    -- Validar usuario
    SELECT EXISTS(
        SELECT 1 FROM tab_Usuarios WHERE id_usuario = p_id_usuario AND activo = TRUE
    ) INTO v_usuario_existe;
    
    IF NOT v_usuario_existe THEN
        RETURN QUERY SELECT 'ERROR', 'Usuario no válido o inactivo';
        RETURN;
    END IF;

    -- Validar método de pago
    SELECT EXISTS(
        SELECT 1 FROM tab_Metodos_Pago WHERE id_metodo_pago = p_id_metodo_pago
    ) INTO v_metodo_existe;
    
    IF NOT v_metodo_existe THEN
        RETURN QUERY SELECT 'ERROR', 'Método de pago no válido';
        RETURN;
    END IF;

    -- Verificar si ya existe una relación
    IF EXISTS (
        SELECT 1 FROM tab_Usuario_Metodo_Pago
        WHERE id_usuario = p_id_usuario AND id_metodo_pago = p_id_metodo_pago
    ) THEN
        -- Actualizar
        UPDATE tab_Usuario_Metodo_Pago
        SET num_tarjeta = p_num_tarjeta,
            fecha_vencimiento = p_fecha_vencimiento,
            usr_update = CURRENT_USER,
            fec_update = CURRENT_TIMESTAMP
        WHERE id_usuario = p_id_usuario AND id_metodo_pago = p_id_metodo_pago;
        
        RETURN QUERY SELECT 'SUCCESS', 'Método de pago actualizado correctamente';
    ELSE
        -- Insertar nuevo
        INSERT INTO tab_Usuario_Metodo_Pago (
            id_usuario_metodo_pago, id_usuario, id_metodo_pago, 
            num_tarjeta, fecha_vencimiento, usr_insert, fec_insert
        ) VALUES (
            (SELECT COALESCE(MAX(id_usuario_metodo_pago), 0) + 1 FROM tab_Usuario_Metodo_Pago),
            p_id_usuario, p_id_metodo_pago, p_num_tarjeta, p_fecha_vencimiento,
            CURRENT_USER, CURRENT_TIMESTAMP
        );
        
        RETURN QUERY SELECT 'SUCCESS', 'Método de pago registrado correctamente';
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        RETURN QUERY SELECT 'ERROR', 'Error: ' || SQLERRM;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fun_insert_pago(
    Pid_orden           tab_Pagos.id_orden%TYPE,
    Pmonto              tab_Pagos.monto%TYPE,
    Pid_metodo_pago     tab_Pagos.id_metodo_pago%TYPE,
    Pestado_pago        tab_Pagos.estado_pago%TYPE DEFAULT 'pendiente',
    Pcomprobante        BYTEA DEFAULT NULL,
    Pextension          VARCHAR DEFAULT NULL
) RETURNS BOOLEAN AS
$$
DECLARE
    v_new_id_pago INT;
BEGIN
    SELECT COALESCE(MAX(id_pago), 0) + 1 INTO v_new_id_pago FROM tab_Pagos;

    INSERT INTO tab_Pagos (
        id_pago, id_orden, monto, id_metodo_pago, estado_pago, fecha_pago,
        comprobante_archivo, comprobante_extension
    ) VALUES (
        v_new_id_pago, Pid_orden, Pmonto, Pid_metodo_pago, Pestado_pago, CURRENT_TIMESTAMP,
        Pcomprobante, Pextension
    );

    RETURN TRUE;
EXCEPTION
    WHEN unique_violation THEN
        RAISE WARNING 'Error: El ID de pago % ya existe o la orden % ya tiene un pago asociado.', v_new_id_pago, Pid_orden;
        RETURN FALSE;
    WHEN foreign_key_violation THEN
        RAISE WARNING 'Error: La orden o el método de pago especificado no existe. Detalles: %', SQLERRM;
        RETURN FALSE;
    WHEN check_violation THEN
        RAISE WARNING 'Error: El monto o el estado del pago no cumplen con las restricciones. Detalles: %', SQLERRM;
        RETURN FALSE;
    WHEN OTHERS THEN
        RAISE WARNING 'Error inesperado al insertar pago: %', SQLERRM;
        RETURN FALSE;
END;
$$
LANGUAGE PLPGSQL;

-- Función para actualizar factura

CREATE OR REPLACE FUNCTION fun_update_pago(
    Kid_pago            tab_Pagos.id_pago%TYPE,
    Kid_orden           tab_Pagos.id_orden%TYPE,
    Kmonto              tab_Pagos.monto%TYPE,
    Kid_metodo_pago     tab_Pagos.id_metodo_pago%TYPE,
    Kestado_pago        tab_Pagos.estado_pago%TYPE
) RETURNS BOOLEAN AS
$$
BEGIN
    UPDATE tab_Pagos SET
        id_orden = Kid_orden,
        monto = Kmonto,
        id_metodo_pago = Kid_metodo_pago,
        estado_pago = Kestado_pago
    WHERE id_pago = Kid_pago;

    IF FOUND THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
END;
$$
LANGUAGE PLPGSQL;


-- Función para actualizar una promoción en tab_Promociones

CREATE OR REPLACE FUNCTION fun_insert_metodos_pago(
    wid_metodo_pago tab_Metodos_Pago.id_metodo_pago%TYPE,
    wnombre_metodo tab_Metodos_Pago.nombre_metodo%TYPE,
    wdescripcion tab_Metodos_Pago.descripcion%TYPE
) RETURNS TEXT AS
$BODY$
BEGIN
    IF EXISTS(SELECT 1 FROM tab_Metodos_Pago WHERE id_metodo_pago = wid_metodo_pago OR nombre_metodo = wnombre_metodo) THEN
        RETURN 'ERROR: El método de pago ya existe';
    END IF;
    
    INSERT INTO tab_Metodos_Pago (id_metodo_pago, nombre_metodo, descripcion)
    VALUES (wid_metodo_pago, wnombre_metodo, wdescripcion);
    
    RETURN 'SUCCESS: Método de pago insertado correctamente';
EXCEPTION WHEN OTHERS THEN
    RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;

-- UPDATE

CREATE OR REPLACE FUNCTION fun_update_metodos_pago(
    wid_metodo_pago tab_Metodos_Pago.id_metodo_pago%TYPE,
    wnombre_metodo tab_Metodos_Pago.nombre_metodo%TYPE,
    wdescripcion tab_Metodos_Pago.descripcion%TYPE
) RETURNS TEXT AS
$BODY$
BEGIN
    UPDATE tab_Metodos_Pago 
    SET nombre_metodo = wnombre_metodo, descripcion = wdescripcion
    WHERE id_metodo_pago = wid_metodo_pago;
    
    IF FOUND THEN
        RETURN 'SUCCESS: Método de pago actualizado correctamente';
    ELSE
        RETURN 'ERROR: No se encontró el método de pago';
    END IF;
EXCEPTION WHEN OTHERS THEN
    RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;

-- DELETE (Hard)

CREATE OR REPLACE FUNCTION fun_delete_metodos_pago(
    wid_metodo_pago tab_Metodos_Pago.id_metodo_pago%TYPE
) RETURNS TEXT AS
$BODY$
BEGIN
    DELETE FROM tab_Metodos_Pago WHERE id_metodo_pago = wid_metodo_pago;
    
    IF FOUND THEN
        RETURN 'SUCCESS: Método de pago eliminado correctamente';
    ELSE
        RETURN 'ERROR: No se encontró el método de pago';
    END IF;
EXCEPTION 
    WHEN FOREIGN_KEY_VIOLATION THEN
        RETURN 'ERROR: No se puede eliminar porque hay usuarios o pagos asociados';
    WHEN OTHERS THEN
        RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;

-- ==========================================
-- CRUD TABLA: tab_Promociones
-- ==========================================

-- INSERT
