-- CRUD_CONTACTO.SQL - Generated by Refactor Script

CREATE OR REPLACE FUNCTION fun_insert_contacto(
    wid_contacto tab_Contacto.id_contacto%TYPE,
    wnombre_remitente tab_Contacto.nombre_remitente%TYPE,
    wcorreo_remitente tab_Contacto.correo_remitente%TYPE,
    wtelefono_remitente tab_Contacto.telefono_remitente%TYPE,
    wasunto tab_Contacto.asunto%TYPE,
    wmensaje tab_Contacto.mensaje%TYPE
) RETURNS TEXT AS
$BODY$
BEGIN
    INSERT INTO tab_Contacto (id_contacto, nombre_remitente, correo_remitente, telefono_remitente, asunto, mensaje, estado)
    VALUES (wid_contacto, wnombre_remitente, wcorreo_remitente, wtelefono_remitente, wasunto, wmensaje, 'pendiente');
    
    RETURN 'SUCCESS: Mensaje de contacto registrado correctamente';
EXCEPTION WHEN OTHERS THEN
    RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;

-- UPDATE

CREATE OR REPLACE FUNCTION fun_update_contacto(
    wid_contacto tab_Contacto.id_contacto%TYPE,
    westado tab_Contacto.estado%TYPE
) RETURNS TEXT AS
$BODY$
BEGIN
    UPDATE tab_Contacto SET estado = westado WHERE id_contacto = wid_contacto;
    
    IF FOUND THEN
        RETURN 'SUCCESS: Estado del contacto actualizado correctamente';
    ELSE
        RETURN 'ERROR: No se encontró el mensaje de contacto';
    END IF;
EXCEPTION WHEN OTHERS THEN
    RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;

-- DELETE (Hard)

CREATE OR REPLACE FUNCTION fun_delete_contacto(
    wid_contacto tab_Contacto.id_contacto%TYPE
) RETURNS TEXT AS
$BODY$
BEGIN
    DELETE FROM tab_Contacto WHERE id_contacto = wid_contacto;
    
    IF FOUND THEN
        RETURN 'SUCCESS: Mensaje de contacto eliminado correctamente';
    ELSE
        RETURN 'ERROR: No se encontró el mensaje de contacto';
    END IF;
EXCEPTION WHEN OTHERS THEN
    RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$ LANGUAGE PLPGSQL;

-- ==========================================
-- CRUD TABLA: tab_Empleados
-- ==========================================

-- INSERT
