-- CRUD_PRODUCTOS.SQL - Generated by Refactor Script

CREATE OR REPLACE FUNCTION fun_actualizar_inventario_rdwatch(
    p_id_producto  tab_Productos.id_producto%TYPE,   -- ID del producto que se va a actualizar
    p_delta_stock  tab_Productos.stock%TYPE   -- Ajuste al stock (puede ser negativo o positivo)
)
RETURNS tab_Productos.stock%TYPE  -- La función retorna el nuevo stock después de la actualización
LANGUAGE plpgsql
AS $$
DECLARE
    v_stock_actual tab_Productos.stock%TYPE;  -- Variable para almacenar el stock actual del producto
    v_stock_nuevo  tab_Productos.stock%TYPE;  -- Variable para almacenar el nuevo stock después del ajuste
BEGIN
    -- Bloqueamos la fila del producto para evitar condiciones de carrera
    -- El FOR UPDATE asegura que la fila del producto se bloquee mientras se realiza el ajuste de stock
    SELECT stock
      INTO v_stock_actual
      FROM tab_Productos
     WHERE id_producto = p_id_producto
     FOR UPDATE;  -- Bloqueo exclusivo de la fila del producto para evitar cambios concurrentes

    -- Verificamos si el producto existe
    IF NOT FOUND THEN
        -- Si no se encuentra el producto, lanzamos una excepción
        RAISE EXCEPTION 'Error: El producto con ID % no existe', p_id_producto;
    END IF;

    -- Si el ajuste al stock es cero, no realizamos ningún cambio
    IF p_delta_stock = 0 THEN
        -- Si no hay cambio, simplemente retornamos el stock actual
        RETURN v_stock_actual;
    END IF;

    -- Calculamos el nuevo stock sumando el ajuste al stock actual
    v_stock_nuevo := v_stock_actual + p_delta_stock;

    -- Validamos que el stock no sea negativo
    -- Si el stock resultante es menor que cero, lanzamos una excepción
    IF v_stock_nuevo < 0 THEN
        RAISE EXCEPTION
            'Error: Stock insuficiente para el producto %. Disponible: %, Ajuste solicitado: %',
            p_id_producto, v_stock_actual, p_delta_stock;
    END IF;

    -- Actualizamos el stock en la tabla de productos
    UPDATE tab_Productos
       SET stock = v_stock_nuevo
     WHERE id_producto = p_id_producto;

    -- Los triggers de auditoría BEFORE UPDATE (fun_audit_rdwatch) completan usr_update y fec_update.
    -- Esto asegura que los campos de auditoría sean actualizados automáticamente durante la actualización.

    -- Retornamos el nuevo stock después de la actualización
    RETURN v_stock_nuevo;
END;
$$;

CREATE OR REPLACE FUNCTION fun_historial_producto(
    wid_producto tab_Productos.id_producto%TYPE
) RETURNS TABLE (
    fecha_movimiento TIMESTAMP,
    tipo_movimiento  TEXT,
    cantidad         BIGINT,
    referencia       TEXT
) AS
$$
BEGIN
    -- =====================================
    -- VALIDAR QUE EL PRODUCTO EXISTA
    -- =====================================
    IF NOT EXISTS (SELECT 1 FROM tab_Productos WHERE id_producto = wid_producto) THEN
        RAISE EXCEPTION 'Error: El producto con ID % no existe', wid_producto;
    END IF;

    -- =====================================
    -- RETORNAR MOVIMIENTOS
    -- =====================================
    RETURN QUERY
    (
        -- Entradas desde recepciones de proveedor
        SELECT 
            r.fecha_recepcion AS fecha_movimiento,
            'Recepción'::TEXT AS tipo_movimiento,
            r.cantidad_recibida AS cantidad,
            ('Proveedor: ' || p.nom_proveedor)::TEXT AS referencia
        FROM tab_Recepciones_Proveedor r
        JOIN tab_Proveedor p ON p.id_proveedor = r.id_proveedor
        WHERE r.id_producto = wid_producto

        UNION ALL

        -- Salidas desde facturas
        SELECT 
            f.fecha_emision AS fecha_movimiento,
            'Venta'::TEXT AS tipo_movimiento,
            -df.cantidad AS cantidad,  -- negativo para salidas
            ('Factura: ' || f.id_factura || ' - Cliente: ' || u.nom_usuario)::TEXT AS referencia
        FROM tab_Detalle_Factura df
        JOIN tab_Facturas f ON f.id_factura = df.id_factura
        JOIN tab_Usuarios u ON u.id_usuario = f.id_usuario
        WHERE df.id_producto = wid_producto
    )
    ORDER BY fecha_movimiento;

END;
$$
LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.fun_insert_productos(
    wid_producto bigint,
    wid_marca bigint,
    wnom_producto character varying,
    wdescripcion text,
    wprecio numeric,
    wid_categoria integer,
    wid_subcategoria integer,
    wstock smallint,
    wurl_imagen character varying DEFAULT NULL::character varying)
    RETURNS text
    LANGUAGE 'plpgsql'
AS $BODY$
DECLARE 
    wproducto tab_Productos.id_producto%TYPE;
    wmarca_existe BOOLEAN := FALSE;
    wcategoria_existe BOOLEAN := FALSE;
    wsubcategoria_existe BOOLEAN := FALSE;
BEGIN
    -- 1. Verificar si ya existe el ID de producto
    SELECT id_producto INTO wproducto FROM tab_Productos WHERE id_producto = wid_producto;
    IF FOUND THEN
        RETURN 'ERROR: El producto con ID ' || wid_producto || ' ya existe';
    END IF;

    -- 2. Verificar Marca (Validación Robustecida)
    -- Buscamos el ID. El estado debe ser TRUE (o NULL, que se asume activo si es el caso, pero aquí forzamos TRUE)
    SELECT EXISTS(
        SELECT 1 
        FROM tab_Marcas 
        WHERE id_marca = wid_marca 
        AND (estado_marca = TRUE OR estado_marca IS TRUE)
    ) INTO wmarca_existe;

    IF NOT wmarca_existe THEN
        -- Debug: Retornar mensaje específico si falla
        RETURN 'ERROR: La marca con ID ' || wid_marca || ' no existe o está inactiva (Verifique tab_Marcas)';
    END IF;

    -- 3. Verificar Categoría
    SELECT EXISTS(
        SELECT 1 FROM tab_Categorias 
        WHERE id_categoria = wid_categoria AND estado = TRUE
    ) INTO wcategoria_existe;
    
    IF NOT wcategoria_existe THEN
        RETURN 'ERROR: La categoría con ID ' || wid_categoria || ' no existe o está inactiva';
    END IF;

    -- 4. Verificar Subcategoría
    SELECT EXISTS(
        SELECT 1 FROM tab_Subcategorias 
        WHERE id_categoria = wid_categoria 
          AND id_subcategoria = wid_subcategoria 
          AND estado = TRUE
    ) INTO wsubcategoria_existe;
    
    IF NOT wsubcategoria_existe THEN
        RETURN 'ERROR: La subcategoría ' || wid_subcategoria || ' no existe o no pertenece a la categoría ' || wid_categoria;
    END IF;

    -- 5. Insertar
    INSERT INTO tab_Productos (
        id_producto, id_marca, nom_producto, descripcion, precio,
        id_categoria, id_subcategoria, stock, url_imagen, estado
    ) VALUES (
        wid_producto, wid_marca, TRIM(wnom_producto), TRIM(wdescripcion), wprecio,
        wid_categoria, wid_subcategoria, wstock,
        CASE WHEN wurl_imagen IS NULL OR TRIM(wurl_imagen) = '' THEN NULL ELSE TRIM(wurl_imagen) END,
        TRUE
    );
    
    RETURN 'SUCCESS: Producto insertado correctamente con ID ' || wid_producto;

EXCEPTION
    WHEN OTHERS THEN
        RETURN 'ERROR SQL: ' || SQLERRM;
END;
$BODY$;

CREATE OR REPLACE FUNCTION fun_update_producto(
    Kid_producto        tab_Productos.id_producto%TYPE,
    Kid_marca           tab_Productos.id_marca%TYPE,
    Knom_producto       tab_Productos.nom_producto%TYPE,
    Kdescripcion        tab_Productos.descripcion%TYPE,
    Kprecio             tab_Productos.precio%TYPE,
    Kid_categoria       tab_Productos.id_categoria%TYPE,
    Kid_subcategoria    tab_Productos.id_subcategoria%TYPE,
    Kstock              tab_Productos.stock%TYPE,
    Kurl_imagen         tab_Productos.url_imagen%TYPE,
    Kestado             tab_Productos.estado%TYPE
) RETURNS BOOLEAN AS
$$
BEGIN
    UPDATE tab_Productos SET
        id_marca = Kid_marca,
        nom_producto = Knom_producto,
        descripcion = Kdescripcion,
        precio = Kprecio,
        id_categoria = Kid_categoria,
        id_subcategoria = Kid_subcategoria,
        stock = Kstock,
        url_imagen = Kurl_imagen,
        estado = Kestado
    WHERE id_producto = Kid_producto;

    IF FOUND THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
END;
$$
LANGUAGE PLPGSQL;


-- Función para actualizar una orden en tab_Orden

CREATE OR REPLACE FUNCTION fun_update_productos(
    wid_producto tab_Productos.id_producto%TYPE,
    wid_marca tab_Productos.id_marca%TYPE,
    wnom_producto tab_Productos.nom_producto%TYPE,
    wdescripcion tab_Productos.descripcion%TYPE,
    wprecio tab_Productos.precio%TYPE,
    wid_categoria tab_Productos.id_categoria%TYPE,
    wid_subcategoria tab_Productos.id_subcategoria%TYPE,
    wstock tab_Productos.stock%TYPE,
    wurl_imagen tab_Productos.url_imagen%TYPE DEFAULT NULL,
    westado tab_Productos.estado%TYPE DEFAULT TRUE
) RETURNS TEXT AS
$BODY$
DECLARE
    wnombre_existente tab_Productos.id_producto%TYPE;
BEGIN
    -- Validar nombre duplicado
    SELECT id_producto INTO wnombre_existente FROM tab_Productos
    WHERE LOWER(TRIM(nom_producto)) = LOWER(TRIM(wnom_producto)) AND id_producto != wid_producto;
    IF FOUND THEN
        RETURN 'ERROR: Ya existe otro producto con el nombre: ' || wnom_producto;
    END IF;

    -- Validar valores básicos
    IF wprecio IS NULL OR wprecio <= 0 THEN
        RETURN 'ERROR: El precio debe ser mayor a cero';
    END IF;

    IF wstock IS NULL OR wstock < 0 THEN
        RETURN 'ERROR: El stock no puede ser negativo';
    END IF;

    -- Actualizar
    UPDATE tab_Productos SET
        id_marca = wid_marca,
        nom_producto = TRIM(wnom_producto),
        descripcion = TRIM(wdescripcion),
        precio = wprecio,
        id_categoria = wid_categoria,
        id_subcategoria = wid_subcategoria,
        stock = wstock,
        url_imagen = CASE WHEN wurl_imagen IS NULL OR TRIM(wurl_imagen) = '' THEN NULL ELSE TRIM(wurl_imagen) END,
        estado = westado
    WHERE id_producto = wid_producto;

    IF FOUND THEN
        RETURN 'SUCCESS: Producto actualizado correctamente';
    ELSE
        RETURN 'ERROR: No se encontró el producto con ID ' || wid_producto;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RETURN 'ERROR: ' || SQLERRM;
END;
$BODY$
LANGUAGE PLPGSQL;


-- DELETE - Eliminar producto (soft delete)

CREATE OR REPLACE FUNCTION fun_delete_productos(
    wid_producto tab_Productos.id_producto%TYPE
) RETURNS TEXT AS
$BODY$
BEGIN
    UPDATE tab_Productos SET estado = FALSE WHERE id_producto = wid_producto;

    IF FOUND THEN
        RETURN 'SUCCESS: Producto desactivado correctamente';
    ELSE
        RETURN 'ERROR: No se encontró el producto con ID ' || wid_producto;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RETURN 'ERROR: ' || SQLERRM;
END;
$BODY$
LANGUAGE PLPGSQL;

-- ==========================================
-- CRUD TABLA: tab_Proveedor 
-- ==========================================

-- INSERT - Insertar proveedor
