-- CRUD_SERVICIOS.SQL - Generated by Refactor Script

CREATE OR REPLACE FUNCTION fun_insert_orden_servicio(
    Pid_orden                   tab_Orden_Servicios.id_orden%TYPE,
    Pid_servicio                tab_Orden_Servicios.id_servicio%TYPE,
    Pcantidad                   tab_Orden_Servicios.cantidad%TYPE,
    Pprecio_servicio_aplicado   tab_Orden_Servicios.precio_servicio_aplicado%TYPE
) RETURNS BOOLEAN AS
$$
DECLARE
    v_new_id_orden_servicio INT;
BEGIN
    SELECT COALESCE(MAX(id_orden_servicio), 0) + 1 INTO v_new_id_orden_servicio FROM tab_Orden_Servicios;

    INSERT INTO tab_Orden_Servicios (
        id_orden_servicio, id_orden, id_servicio, cantidad, precio_servicio_aplicado
    ) VALUES (
        v_new_id_orden_servicio, Pid_orden, Pid_servicio, Pcantidad, Pprecio_servicio_aplicado
    );

    RETURN TRUE;
EXCEPTION
    WHEN unique_violation THEN
        RAISE WARNING 'Error: El ID de servicio de orden % ya existe o el servicio % ya está en la orden %.', v_new_id_orden_servicio, Pid_servicio, Pid_orden;
        RETURN FALSE;
    WHEN foreign_key_violation THEN
        RAISE WARNING 'Error: La orden o el servicio especificado no existe. Detalles: %', SQLERRM;
        RETURN FALSE;
    WHEN check_violation THEN
        RAISE WARNING 'Error: La cantidad o el precio del servicio no cumplen con las restricciones. Detalles: %', SQLERRM;
        RETURN FALSE;
    WHEN OTHERS THEN
        RAISE WARNING 'Error inesperado al insertar servicio de orden: %', SQLERRM;
        RETURN FALSE;
END;
$$
LANGUAGE PLPGSQL;

-- Función para insertar una nueva factura

CREATE OR REPLACE FUNCTION fun_registrar_peticion_servicio(
    p_id_usuario    tab_Usuarios.id_usuario%TYPE,
    p_id_servicio   tab_Servicios.id_servicio%TYPE,
    p_fecha_pref    DATE DEFAULT CURRENT_DATE,
    p_notas         TEXT DEFAULT NULL,
    p_prioridad     TEXT DEFAULT 'normal'
) RETURNS BIGINT AS
$$
DECLARE
    v_usr         RECORD;
    v_srv         RECORD;
    v_id_reserva  BIGINT;
BEGIN
    -- 1. VALIDAR USUARIO ACTIVO
    SELECT id_usuario, nom_usuario, activo INTO v_usr
    FROM tab_Usuarios WHERE id_usuario = p_id_usuario;

    IF NOT FOUND THEN RAISE EXCEPTION 'Error: El usuario no existe'; END IF;
    IF v_usr.activo = FALSE THEN RAISE EXCEPTION 'Error: Usuario inactivo'; END IF;

    -- 2. VALIDAR SERVICIO (Eliminamos la restricción de nombres fijos)
    SELECT id_servicio, nom_servicio INTO v_srv
    FROM tab_Servicios WHERE id_servicio = p_id_servicio;

    IF NOT FOUND THEN RAISE EXCEPTION 'Error: El servicio no existe'; END IF;

    -- 3. VALIDAR FECHA
    IF p_fecha_pref < CURRENT_DATE THEN
        RAISE EXCEPTION 'Error: La fecha no puede ser anterior a hoy';
    END IF;

    -- 4. INSERTAR RESERVA
    SELECT COALESCE(MAX(id_reserva),0) + 1 INTO v_id_reserva FROM tab_Reservas;

    INSERT INTO tab_Reservas (
        id_reserva, id_usuario, id_servicio, fecha_solicitada, fecha_preferida,
        notas_cliente, estado_reserva, prioridad, usr_insert, fec_insert
    ) VALUES (
        v_id_reserva, p_id_usuario, p_id_servicio, CURRENT_TIMESTAMP, p_fecha_pref,
        NULLIF(TRIM(p_notas),''), 'pendiente', p_prioridad, CURRENT_USER, CURRENT_TIMESTAMP
    );

    RETURN v_id_reserva;
EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'Error: %', SQLERRM;
        RETURN -1;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fun_insert_servicios(
    wid_servicio tab_Servicios.id_servicio%TYPE,
    wnom_servicio tab_Servicios.nom_servicio%TYPE,
    wdescripcion tab_Servicios.descripcion%TYPE,
    wprecio_servicio tab_Servicios.precio_servicio%TYPE,
    wduracion_estimada tab_Servicios.duracion_estimada%TYPE
) RETURNS TEXT AS
$BODY$
    DECLARE wservicio tab_Servicios.id_servicio%TYPE;
    BEGIN
        -- Verificar si ya existe un servicio con el mismo ID o nombre
        SELECT id_servicio INTO wservicio FROM tab_Servicios
        WHERE id_servicio = wid_servicio OR nom_servicio = wnom_servicio;
        
        IF FOUND THEN
            RETURN 'ERROR: Servicio ya existe con ese ID o nombre';
        ELSE
            BEGIN
                INSERT INTO tab_Servicios (id_servicio, nom_servicio, descripcion, precio_servicio, duracion_estimada)
                VALUES (wid_servicio, wnom_servicio, wdescripcion, wprecio_servicio, wduracion_estimada);
                
                RETURN 'SUCCESS: Servicio insertado correctamente con ID ' || wid_servicio;
            EXCEPTION
                WHEN OTHERS THEN
                    RETURN 'ERROR: ' || SQLERRM;
            END;
        END IF;
    END;
$BODY$
LANGUAGE PLPGSQL;

-- UPDATE - Actualizar servicio

CREATE OR REPLACE FUNCTION fun_update_servicios(
    wid_servicio tab_Servicios.id_servicio%TYPE,
    wnom_servicio tab_Servicios.nom_servicio%TYPE,
    wdescripcion tab_Servicios.descripcion%TYPE,
    wprecio_servicio tab_Servicios.precio_servicio%TYPE,
    wduracion_estimada tab_Servicios.duracion_estimada%TYPE
) RETURNS TEXT AS
$BODY$
    DECLARE
        wnombre_existente tab_Servicios.id_servicio%TYPE;
    BEGIN
        -- Verificar si el nuevo nombre ya existe en otro servicio
        SELECT id_servicio INTO wnombre_existente FROM tab_Servicios
        WHERE nom_servicio = wnom_servicio AND id_servicio != wid_servicio;
        
        IF FOUND THEN
            RETURN 'ERROR: Ya existe otro servicio con ese nombre';
        END IF;
        
        -- Realizar la actualización
        UPDATE tab_Servicios SET 
            nom_servicio = wnom_servicio,
            descripcion = wdescripcion,
            precio_servicio = wprecio_servicio,
            duracion_estimada = wduracion_estimada
        WHERE id_servicio = wid_servicio;
        
        IF FOUND THEN
            RETURN 'SUCCESS: Servicio actualizado correctamente';
        ELSE
            RETURN 'ERROR: No se encontró el servicio con ID ' || wid_servicio;
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 'ERROR: ' || SQLERRM;
    END;
$BODY$
LANGUAGE PLPGSQL;

-- DELETE - Eliminar servicio (hard delete)

CREATE OR REPLACE FUNCTION fun_delete_servicios(
    wid_servicio tab_Servicios.id_servicio%TYPE
) RETURNS TEXT AS
$BODY$
    BEGIN
        DELETE FROM tab_Servicios WHERE id_servicio = wid_servicio;
        IF FOUND THEN
            RETURN 'SUCCESS: Servicio eliminado correctamente';
        ELSE
            RETURN 'ERROR: No se encontró el servicio con ID ' || wid_servicio;
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 'ERROR: ' || SQLERRM;
    END;
$BODY$
LANGUAGE PLPGSQL;

-- ==========================================
-- CRUD TABLA: tab_Orden 
-- ==========================================

-- INSERT - Insertar orden
